<html>
<head>
    <meta charset="utf-8"/>
    <title>PARSER</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css"
          integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-2.1.4.min.js"></script>

</head>
<body>


<br>

<div class="container">
    <h3><?php echo $title ?> <a href="/">home</a></h3>

    <div class="row">
        <div class="col-md-12">
