<?php include 'header.phtml'; ?>

<table class="table table-condensed">
    <thead>
    <th>id</th>
    <th>Парсер</th>
    <th>Тип</th>
    <th>Параметры</th>
    <th>состояние</th>
    <th>Результаты</th>
    <th>Количество</th>
    <th>
        <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#addParserModal">
            Создать парсер
        </button>
    </th>
    </thead>
    <tbody class="list_parser">

    <?php include_once 'list.phtml' ?>
    </tbody>
</table>
</div>
</div>


<!-- Modal -->
<div class="modal fade" id="addParserModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span
                        aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="myModalLabel">Создание парсера</h4>
            </div>
            <div class="modal-body">
                <form class="paramForm">
                    <b>Название парсера:</b><br>
                    <input type="text" name="header" class="form-control" required>
                    <br>
                    <b>Тип парсера:</b><br>

                    <label for="MailRangeUser">(MailRangeUser)По диапозону <input type="radio" id="MailRangeUser" name="type"
                                                                     value="Mail\RangeUser"></label><br>
                    <label for="MailRange">(Mail)По диапозону <input type="radio" id="MailRange" name="type"
                                                                        value="Mail\Range"></label><br>
                    <label for="RamblerRange">(Rambler)По диапозону <input type="radio" id="RamblerRange" name="type"
                                                                           value="Rambler\Range"></label><br>
                    <label for="RamblerCategory">(Rambler)По категории <input type="radio" name="type"
                                                                           value="Rambler\Category" id="RamblerCategory" ></label><br>
                    <label for="RamblerSearch">(Rambler)По ключевому слову <input type="radio" name="type"
                                                                                 value="Rambler\Search"  id="RamblerSearch" ></label><br><br>
                    <b>Парметры:</b><br>
                    <textarea name="param" required></textarea>
                </form>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                <button type="button" class="btn btn-primary add_action_parser">Сохранить</button>
            </div>
        </div>
    </div>
</div>

<script type="text/javascript">

    $(document).ready(function () {


        window.setInterval(update, 3000);


        //status
        $('.list_parser').on('click', '.action_status_parser', function () {
            form = $(".paramForm");
            var action = $(this).attr('action_parser');
            var id = $(this).attr('id_parser');
            $.ajax({
                url: "/parser/status",
                data: {id: id, event: action},
                success: function (data) {
                    console.log(data);
                    if (data.status == 'ok') {
                        update();
                    } else {
                        //alert(data.message);
                    }
                }
            });
        });

        //remove
        $('.list_parser').on('click', '.delete_action_parser', function () {
            var id = $(this).attr('id_parser');
            $.ajax({
                url: "/parser/remove",
                data: {id: id},
                dataType: 'json',
                success: function (data) {
                    console.log(data);
                    if (data.status == 'ok') {
                        update();
                    } else {
                        alert(data.message);
                    }
                }
            });
        });

        $('.add_action_parser').on('click', function () {
            var fields = $(".paramForm").serializeArray();
            console.log(fields);
            fields_send = {};
            for (field in fields) {

                fields_send[fields[field].name] = fields[field].value;

            }
            $.ajax({
                url: "/parser/add",
                data: fields_send,
                dataType: 'json',
                success: function (data) {
                    console.log(data);
                    if (data.status == 'ok') {
                        $("#addParserModal").modal('hide');
                        update();
                    } else {
                        alert(data.message);
                    }

                }
            });

        });

    });
    function update() {
        $.ajax({
            url: "/update/4",
            success: function (data) {
                $('.list_parser').html(data);
            }
        });
    }

</script>
<?php include 'footer.phtml'; ?>
